// Command gencommands generates the pinned Vim Ex command table.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	vimTag    = "v9.2.1015"
	vimCommit = "5ab969f719bb09555e90e8dff8c94fc37bcbf2ae"
)

var commandPattern = regexp.MustCompile(`(?s)EXCMD\(CMD_[^,]+,\s*"([^"]+)",\s*[^,]+,\s*(?://[^\n]*\n\s*)?([A-Z0-9_|\s]+),\s*ADDR_[A-Z0-9_]+\s*\)`) //nolint:lll

func main() {
	vimRoot := flag.String("vim-root", "", "path to the official Vim Git checkout")
	output := flag.String("output", "internal/vimdata/commands_generated.go", "generated Go file")
	flag.Parse()
	if *vimRoot == "" {
		*vimRoot = os.Getenv("VIM_SOURCE")
	}
	if *vimRoot == "" {
		fatalf("set -vim-root or VIM_SOURCE")
	}

	resolved, err := exec.Command("git", "-C", *vimRoot, "rev-list", "-n", "1", vimTag).Output()
	if err != nil || strings.TrimSpace(string(resolved)) != vimCommit {
		fatalf("%s in %s does not resolve to pinned commit %s", vimTag, *vimRoot, vimCommit)
	}
	source, err := exec.Command("git", "-C", *vimRoot, "show", vimTag+":src/ex_cmds.h").Output()
	if err != nil {
		fatalf("read ex_cmds.h: %v", err)
	}
	matches := commandPattern.FindAllSubmatch(source, -1)
	if len(matches) != 600 {
		fatalf("found %d commands, want 600", len(matches))
	}

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by tools/gencommands from Vim v9.2.1015; DO NOT EDIT.")
	fmt.Fprintln(&generated, "package vimdata")
	fmt.Fprintln(&generated, "")
	fmt.Fprintln(&generated, "var commands = [...]Command{")
	for _, match := range matches {
		name := string(match[1])
		flags := strings.FieldsFunc(string(match[2]), func(r rune) bool {
			return r == '|' || r == ' ' || r == '\t' || r == '\r' || r == '\n'
		})
		var selected []string
		for _, item := range flags {
			switch item {
			case "EX_BANG":
				selected = append(selected, "AllowBang")
			case "EX_TRLBAR":
				selected = append(selected, "AllowBar")
			case "EX_NOTRLCOM":
				selected = append(selected, "NoTrailingComment")
			case "EX_EXPR_ARG":
				selected = append(selected, "ExpressionArgument")
			case "EX_NEEDARG":
				selected = append(selected, "NeedArgument")
			case "EX_WHOLE":
				selected = append(selected, "ExactInVim9")
			}
		}
		flagExpression := "0"
		if len(selected) > 0 {
			flagExpression = strings.Join(selected, " | ")
		}
		fmt.Fprintf(&generated, "\t{Name: %q, Flags: %s},\n", name, flagExpression)
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format output: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "gencommands: "+format+"\n", arguments...)
	os.Exit(1)
}
