// Command gencommands generates the pinned Vim Ex command table.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/neoclide/vimls-go/tools/internal/vimhelp"
)

const (
	vimTag    = "v9.2.1015"
	vimCommit = "5ab969f719bb09555e90e8dff8c94fc37bcbf2ae"
)

var commandPattern = regexp.MustCompile(`(?s)EXCMD\(CMD_[^,]+,\s*"([^"]+)",\s*[^,]+,\s*(?://[^\n]*\n\s*)?([A-Z0-9_|\s]+),\s*ADDR_[A-Z0-9_]+\s*\)`) //nolint:lll

type command struct {
	Name                string
	Flags               string
	Documentation       string
	DocumentationSource string
}

func main() {
	vimRoot := flag.String("vim-root", "", "path to the official Vim Git checkout")
	output := flag.String("output", "internal/vimdata/commands_generated.go", "generated Go file")
	flag.Parse()
	if *vimRoot == "" {
		*vimRoot = os.Getenv("VIM_SOURCE")
	}
	if *vimRoot == "" {
		fatalf("set -vim-root or VIM_SOURCE")
	}

	resolved, err := exec.Command("git", "-C", *vimRoot, "rev-list", "-n", "1", vimTag).Output()
	if err != nil || strings.TrimSpace(string(resolved)) != vimCommit {
		fatalf("%s in %s does not resolve to pinned commit %s", vimTag, *vimRoot, vimCommit)
	}
	source, err := exec.Command("git", "-C", *vimRoot, "show", vimTag+":src/ex_cmds.h").Output()
	if err != nil {
		fatalf("read ex_cmds.h: %v", err)
	}
	matches := commandPattern.FindAllSubmatch(source, -1)
	if len(matches) != 600 {
		fatalf("found %d commands, want 600", len(matches))
	}
	commands := make([]command, 0, len(matches))
	for _, match := range matches {
		commands = append(commands, command{Name: string(match[1]), Flags: generatedFlagExpression(match[2])})
	}
	if err := addDocumentation(*vimRoot, commands); err != nil {
		fatalf("read command documentation: %v", err)
	}

	var generated bytes.Buffer
	fmt.Fprintf(&generated, "// Code generated by tools/gencommands from Vim %s (%s); DO NOT EDIT.\n", vimTag, vimCommit)
	fmt.Fprintln(&generated, "// Documentation is derived from Vim runtime help; see LICENSES/VIM.txt.")
	fmt.Fprintln(&generated, "package vimdata")
	fmt.Fprintln(&generated, "")
	fmt.Fprintf(&generated, "const (\n\tCommandVimTag = %q\n\tCommandVimCommit = %q\n)\n\n", vimTag, vimCommit)
	fmt.Fprintln(&generated, "var commands = [...]Command{")
	for _, command := range commands {
		fmt.Fprintf(&generated, "\t{Name: %q, Flags: %s, Documentation: %q, DocumentationSource: %q},\n", command.Name, command.Flags, command.Documentation, command.DocumentationSource)
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format output: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func addDocumentation(root string, commands []command) error {
	tagsSource, err := readRevisionFile(root, "runtime/doc/tags")
	if err != nil {
		return err
	}
	tagFiles, err := vimhelp.ParseTags(tagsSource)
	if err != nil {
		return err
	}
	byFile := make(map[string][]string)
	commandTags := make(map[string]string, len(commands))
	for _, command := range commands {
		tag := ":" + command.Name
		if command.Name == "*" {
			tag = ":star"
		}
		filename := tagFiles[tag]
		if filename == "" {
			if command.Name == "{" || command.Name == "}" {
				continue
			}
			return fmt.Errorf("help tag %s not found", tag)
		}
		commandTags[command.Name] = tag
		byFile[filename] = append(byFile[filename], tag)
	}
	filenames := make([]string, 0, len(byFile))
	for filename := range byFile {
		filenames = append(filenames, filename)
	}
	sort.Strings(filenames)
	documentation := make(map[string]vimhelp.Documentation, len(commands))
	for _, filename := range filenames {
		source, err := readRevisionFile(root, "runtime/doc/"+filename)
		if err != nil {
			return err
		}
		docs, err := vimhelp.Extract(filename, source, byFile[filename])
		if err != nil {
			return err
		}
		maps.Copy(documentation, docs)
	}
	for index := range commands {
		tag := commandTags[commands[index].Name]
		if tag == "" {
			continue
		}
		doc := documentation[tag]
		if doc.Markdown == "" || doc.Source == "" {
			return fmt.Errorf("documentation for %s is empty", commands[index].Name)
		}
		commands[index].Documentation = doc.Markdown
		commands[index].DocumentationSource = doc.Source
	}
	return nil
}

func readRevisionFile(root, path string) ([]byte, error) {
	output, err := exec.Command("git", "-C", root, "show", vimTag+":"+path).Output()
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return output, nil
}

func generatedFlagExpression(value []byte) string {
	flags := strings.FieldsFunc(string(value), func(r rune) bool {
		return r == '|' || r == ' ' || r == '\t' || r == '\r' || r == '\n'
	})
	var selected []string
	for _, item := range flags {
		switch item {
		case "EX_BANG":
			selected = append(selected, "AllowBang")
		case "EX_TRLBAR":
			selected = append(selected, "AllowBar")
		case "EX_NOTRLCOM":
			selected = append(selected, "NoTrailingComment")
		case "EX_EXPR_ARG":
			selected = append(selected, "ExpressionArgument")
		case "EX_NEEDARG":
			selected = append(selected, "NeedArgument")
		case "EX_WHOLE":
			selected = append(selected, "ExactInVim9")
		case "EX_XFILE", "EX_FILES", "EX_FILE1":
			selected = append(selected, "FileArgument")
		case "EX_EXPORT":
			selected = append(selected, "Exportable")
		case "EX_NONWHITE_OK":
			selected = append(selected, "AllowNonWhite")
		}
	}
	if len(selected) == 0 {
		return "0"
	}
	return strings.Join(selected, " | ")
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "gencommands: "+format+"\n", arguments...)
	os.Exit(1)
}
