// Command genmetadata generates pinned Vim metadata tables.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var commandPattern = regexp.MustCompile(`(?s)EXCMD\(CMD_[^,]+,\s*"([^"]+)",\s*[^,]+,\s*(?://[^\n]*\n\s*)?([A-Z0-9_|\s]+),\s*ADDR_[A-Z0-9_]+\s*\)`) //nolint:lll

type command struct {
	Name  string
	Flags string
}

func generateCommands(vimRoot, output string) error {
	source, err := readRevisionFile(vimRoot, "src/ex_cmds.h")
	if err != nil {
		return err
	}
	matches := commandPattern.FindAllSubmatch(source, -1)
	if len(matches) != 600 {
		return fmt.Errorf("found %d commands, want 600", len(matches))
	}
	commands := make([]command, 0, len(matches))
	for _, match := range matches {
		commands = append(commands, command{Name: string(match[1]), Flags: generatedFlagExpression(match[2])})
	}

	var generated bytes.Buffer
	fmt.Fprintf(&generated, "// Code generated by tools/genmetadata from Vim %s (%s); DO NOT EDIT.\n", vimTag, vimCommit)
	fmt.Fprintln(&generated, "package vimdata")
	fmt.Fprintln(&generated, "")
	fmt.Fprintf(&generated, "const (\n\tCommandVimTag = %q\n\tCommandVimCommit = %q\n)\n\n", vimTag, vimCommit)
	fmt.Fprintln(&generated, "var commands = [...]Command{")
	for _, command := range commands {
		fmt.Fprintf(&generated, "\t{Key: %q, Name: %q, Flags: %s},\n", ":"+command.Name, command.Name, command.Flags)
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return fmt.Errorf("format output: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}

func generatedFlagExpression(value []byte) string {
	flags := strings.FieldsFunc(string(value), func(r rune) bool {
		return r == '|' || r == ' ' || r == '\t' || r == '\r' || r == '\n'
	})
	var selected []string
	for _, item := range flags {
		switch item {
		case "EX_BANG":
			selected = append(selected, "AllowBang")
		case "EX_TRLBAR":
			selected = append(selected, "AllowBar")
		case "EX_NOTRLCOM":
			selected = append(selected, "NoTrailingComment")
		case "EX_EXPR_ARG":
			selected = append(selected, "ExpressionArgument")
		case "EX_NEEDARG":
			selected = append(selected, "NeedArgument")
		case "EX_WHOLE":
			selected = append(selected, "ExactInVim9")
		case "EX_XFILE", "EX_FILES", "EX_FILE1":
			selected = append(selected, "FileArgument")
		case "EX_EXPORT":
			selected = append(selected, "Exportable")
		case "EX_NONWHITE_OK":
			selected = append(selected, "AllowNonWhite")
		case "EX_CMDARG":
			selected = append(selected, "AllowCommandArgument")
		case "EX_ARGOPT":
			selected = append(selected, "AllowArgumentOptions")
		}
	}
	if len(selected) == 0 {
		return "0"
	}
	return strings.Join(selected, " | ")
}
